# Generated by Django 5.2.7 on 2025-11-29 05:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('lms', '0004_course_average_rating_course_total_reviews_review'),
    ]

    operations = [
        migrations.AddField(
            model_name='course',
            name='total_enrollments',
            field=models.IntegerField(default=0),
        ),
    ]
