# Generated by Django 5.2.7 on 2025-11-29 07:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('lms', '0006_certificate'),
    ]

    operations = [
        migrations.AddField(
            model_name='lesson',
            name='video_file',
            field=models.FileField(blank=True, help_text='Upload MP4 video file', null=True, upload_to='lessons/videos/'),
        ),
        migrations.AlterField(
            model_name='lesson',
            name='video_url',
            field=models.CharField(blank=True, help_text='YouTube URL or direct MP4 file URL', max_length=500, null=True),
        ),
    ]
