# Generated by Django 5.2.7 on 2025-11-29 09:10

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('lms', '0007_lesson_video_file_alter_lesson_video_url'),
    ]

    operations = [
        migrations.CreateModel(
            name='StudentCourseProgress',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('overall_progress', models.FloatField(default=0.0, help_text='Overall progress percentage (0-100)')),
                ('last_access', models.DateTimeField(auto_now=True, help_text='Last time student accessed this course')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('course', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='student_progress', to='lms.course')),
                ('student', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='course_progress', to='lms.student')),
            ],
            options={
                'verbose_name': 'Student Course Progress',
                'verbose_name_plural': 'Student Course Progress',
                'ordering': ['-last_access'],
                'indexes': [models.Index(fields=['course', 'overall_progress'], name='lms_student_course__580ab9_idx'), models.Index(fields=['student', 'course'], name='lms_student_student_c2a049_idx')],
                'unique_together': {('student', 'course')},
            },
        ),
    ]
