# Generated by Django 5.2.7 on 2025-11-29 15:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('lms', '0010_notification'),
    ]

    operations = [
        migrations.AddField(
            model_name='student',
            name='bio',
            field=models.TextField(blank=True, help_text='Mô tả cá nhân', null=True),
        ),
    ]
